### ISSUE TITLE
Missing steps in documentation

### ISSUE THREAD

**Issue by romanpeters** [svsticky/sadserver#159]
While setting up a new staging environment from scratch, [the documentation](https://github.com/svsticky/sadserver/blob/master/README.md) was missing a few steps.

To me, the following was unclear:
- Which settings to apply on digitalocean.com (create a droplet, assign a floating IP, etc.)
- Setting up git submodule is mentioned at the top, but not in the instructions itself
- When running `bootstrap-new-host.yml`, the sudo password should be empty
- When receiving the Ansible password, it says to save it, but doesn't explicitly say which lastpass entry to overwrite. Might also be useful to mention it's the SUDO password, since that's how it's referred to on the next step when you need to enter it.

**Comment by tomwassenberg** [comment]
Fixed in #169 by @romanpeters.
