### ISSUE TITLE
Automate the cycling of secrets

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/sadserver#167]
Recently (#141) I cycled all secrets, which still had to be done because of the new board. It was quite a pain to manually change all secrets, so we should find a way to script this. Since this will have to be done from time to time.

Before doing it manually, I tried automating this into a playbook, but I don't think this is possible (in a neat way) with stock Ansible functionality.

**Comment by arianvp** [comment]
#141

**Comment by tomwassenberg** [comment]
The first thing to do to make this easier, is to get rid of most MySQL passwords, because we don't need them. We can use socket authentication instead for most things, see #195.

**Comment by Riscky** [comment]
Not necessary anymore since we are implementing a Ansible/Bitwarden plugin
