### ISSUE TITLE
Move to Digitalocean Spaces?

### ISSUE THREAD

**Issue by arianvp** [svsticky/sadserver#168]
To have less spread around infra, we could switch to Digitalocean spaces instead of AWS S3. Both are API compatible.

Spaces doesn't support automatic pruning like AWS but we could easily script this.

Questions:
- [ ] How much does AWS currently cost?
- [ ] Is spaces more expensive?
- [ ] Implement https://gist.github.com/barryrld/b4bbedfa63169e0857b4571d1016054e for automatic pruning

**Comment by tomwassenberg** [comment]
Apparently we don't have to use the "hacky" example in the OP to enable automatic pruning of old backups, because Spaces [does support Bucket Lifecycle Rules](https://developers.digitalocean.com/documentation/spaces/#create-bucket-lifecycle), similar to S3. They're just not available in the GUI, but only in the API.

**Comment by duijf** [comment]
Good news with the lifetime stuff.

That with the keys seems like a big oversight and I hope that isn't the case :/

**Comment by tomwassenberg** [comment]
I think it's something that has yet to be implemented, because my assumption is based on (apart from not being able to find the options in the GUI) [this feature request](https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/31525411-spaces-custom-api-key-permissions).

**Comment by tomwassenberg** [comment]
Discussed this with @maartenberg and decided to hold off on this for now, because of the API key issue, which we deem too risky. We should check up on abovementioned issue on their Uservoice, to re-consider the move when that is fixed.

Costs vs. S3 would not be the issue.
