### ISSUE TITLE
fetch-keys-for-gh-user.sh non-functional

### ISSUE THREAD

**Issue by RobinSikkens** [svsticky/sadserver#183]
This script tries to write a to `/ansible/group_vars/all/ssh_keys/`, which has been moved to the secrets repository. 

As such the script is currently non-functional.

**Comment by duijf** [comment]
Have you fetched the git submodules correctly?

**Comment by tomwassenberg** [comment]
See docs: https://github.com/svsticky/sadserver#on-your-local-terminal

**Comment by RobinSikkens** [comment]
It was a mistake on my end. It works now.
