### ISSUE TITLE
Use ruby's apt package instead of compilation

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/sadserver#191]
Now that we're on Ubuntu 18.04, Ruby 2.5.1 (that Koala has been using for a while) is available in the standard repositories.

Currently we compile it ourselves at deploy time, which takes ages (ok, 15-20 mins) and by far takes up the most time of setting up a server from scratch.

So as we decided, we should replace the current build tasks by just installing the apt package.

**Comment by Riscky** [comment]
Irrelevant because of Nix
