### ISSUE TITLE
Post Koala's Sentry alerts as GitHub issues

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/sadserver#194]
Creating an issue, because it wasn't there yet.

WIP in https://github.com/svsticky/aas/

Relevant Sentry plugin issue:  ([link](https://github.com/getsentry/sentry-plugins/issues/94#issuecomment-423581625))

**Comment by Riscky** [comment]
We decided against this because the risk of leaking user information to a public repository is too large
