### ISSUE TITLE
Support more than one oauth2 application at a time

### ISSUE THREAD

**Issue by arianvp** [svsticky/sadserver#199]
For this, we need to run one `oauth2_proxy` per oauth application.     We can accomplish this with a systemd template unit.

**Comment by tomwassenberg** [comment]
For the internal listen address of `oauth2_proxy`, we should probably use Unix sockets instead of TCP. We can then use the website name as part of the socket path, to make the paths (that go in the nginx configs) deterministic but unique for each authenticated website :)

**Comment by arianvp** [comment]
This already works!
