### ISSUE TITLE
Back-up photos from Flickr

### ISSUE THREAD

**Issue by tomwassenberg** [svsticky/sadserver#202]
https://blog.flickr.net/en/2018/12/17/important-service-updates-and-dates-to-remember/

Flickr will start deleting our photos on February 5th. @Ckef has made a local backup, but the regular procedure apparently doesn't retain the album structure, nor any metadata on the photo's themselves. This would make restoring the back-up to pxl next to impossible, assuming we want to at least classify the photos per activity.

There are apparently also other possibilities, like exporting photos per album, which is tedious and error-prone to do manually. We should look into the possibilities here (e.g. write a script for this), very soon though.

**Comment by duijf** [comment]
Oh I didn't know we lost the metadata there; that's cause for concern. Pixel has been designed with albums in mind, so ideally we get an export with that information preserved. Even more ideally, we preserve the order that the activities took place in.

I found https://flickrdownloadr.com/ which looks promising. I hope we can just run that and have it work

**Comment by duijf** [comment]
If that downloader does not do what we want, it seems like we can use the Flickr API. There is [`flickr.photosets.getPhotos`](https://www.flickr.com/services/api/flickr.photosets.getPhotos.html). If the IDs in there match the filenames of the backup we already have, it seems like we should be good. Then it's just a matter of fetching all photosets and downloading the list of images they have.

Do we have the creds for the flickr account somewhere in Bitwarden already?

**Comment by tomwassenberg** [comment]
> Do we have the creds for the flickr account somewhere in Bitwarden already?

I don't see 'em, maybe @Ckef can add those?

**Comment by Ckef** [comment]
They're in the LastPass account, can I share them with you @duijf ?

**Comment by Ckef** [comment]
Another thing: Today this issue made it to our board meeting. If downloading the photos with album information has not been succesful before the **22nd of january** we'll start sorting them manually into albums. We have an IT Crowd sesh at that date so I'll poll if the job's done that day ;)

**Comment by duijf** [comment]
> They're in the LastPass account, can I share them with you @duijf ?

I got rid of my personal LastPass. Could you add them to the IT Crowd Bitwarden? Otherwise, let's discuss offline on Tuesday

**Comment by arianvp** [comment]
Has anyone looked at the EXIF data of the photos? Perhaps flickr stores album information in there.

**Comment by Ckef** [comment]
> I got rid of my personal LastPass. Could you add them to the IT Crowd Bitwarden? Otherwise, let's discuss offline on Tuesday

Oh damn seems I lost the login for bitwarden with a new ubuntu installation.. We'll discuss it Tuesday!

> > Has anyone looked at the EXIF data of the photos? Perhaps flickr stores album information in there.
> 
> In chat, @Ckef said that the metadata was stripped from the photos in the backup he made. I assume he was talking about the EXIF data. But maybe they'll be included when we make a new back-up using the tool @duijf found or the API directly.

Just checked it again, exif readout of some random photo:

```
EXIF tags in 'dscn3871_15238796352_o.jpg' ('Intel' byte order):
--------------------+----------------------------------------------------------
Tag                 |Value
--------------------+----------------------------------------------------------
Image Description   |                               
Manufacturer        |NIKON
Model               |COOLPIX P7000
Orientation         |Top-left
X-Resolution        |300
Y-Resolution        |300
Resolution Unit     |Inch
Software            |COOLPIX P7000V1.1              
Date and Time       |2014:09:01 10:14:10
YCbCr Positioning   |Co-sited
Compression         |JPEG compression
X-Resolution        |300
Y-Resolution        |300
Resolution Unit     |Inch
Exposure Time       |1/30 sec.
F-Number            |f/2,8
Exposure Program    |Normal program
ISO Speed Ratings   |200
Exif Version        |Exif Version 2.2
Date and Time (Origi|2014:09:01 10:14:10
Date and Time (Digit|2014:09:01 10:14:10
Components Configura|Y Cb Cr -
Compressed Bits per | 2
Exposure Bias       |0,00 EV
Maximum Aperture Val|3,00 EV (f/2,8)
Metering Mode       |Pattern
Light Source        |Unknown
Flash               |Flash fired, auto mode
Focal Length        |6,0 mm
Maker Note          |4721 bytes undefined data
User Comment        |                                                          
FlashPixVersion     |FlashPix Version 1.0
Color Space         |sRGB
Pixel X Dimension   |3648
Pixel Y Dimension   |2736
File Source         |DSC
Scene Type          |Directly photographed
Custom Rendered     |Normal process
Exposure Mode       |Auto exposure
White Balance       |Auto white balance
Digital Zoom Ratio  |0,00
Focal Length in 35mm|28
Scene Capture Type  |Standard
Gain Control        |Low gain up
Contrast            |Normal
Saturation          |Normal
Sharpness           |Normal
Subject Distance Ran|Unknown
Interoperability Ind|R98
Interoperability Ver|0100
--------------------+----------------------------------------------------------
EXIF data contains a thumbnail (5334 bytes).
```

Apparently it does show the date and time, but for some reason standard programs (including those on windows) can't read it. But as you can see no album data or anything.

**Comment by tomwassenberg** [comment]
@maartenberg Think we can close this, right? We can use #174 for tracking the transfer to the production bucket.
