### ISSUE TITLE
Koala: MailChimp sync

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#204]
https://github.com/svsticky/constipated-koala/pull/398

- [ ] We already run Redis for Pretix, check if there's no Pretix-specific stuff
- [ ] Requires changes in MailChimp groups, password is now in Bitwarden.
- [ ] New service: sidekiq
- [ ] Webhook
- [ ] Migrate existing subscriptions somehow?

**Comment by Riscky** [comment]
this is fixed :)
