### ISSUE TITLE
Aggressive caching for ActiveStorage-managed files

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#208]
Koala now makes use of ActiveStorage for the poster files, which changes some things in how uploaded files are handled. Behind the scenes, an uploaded file is represented using a blob object, which has an unique URL that will change when a new file is uploaded.

We now can, and probably should, enable more aggressive caching on the files, probably in nginx.

**Comment by Riscky** [comment]
This has been fixed in #332
