### ISSUE TITLE
Static-sticky + Aas deployen

### ISSUE THREAD

**Issue by Riscky** [svsticky/sadserver#210]
see #209 

TODO:

- [x] script om website opnieuw te builden, dit script moet symlinks misbruiken om te zorgen dat er in één keer geswitched wordt naar de nieuwe build
- [x] service om dit script te callen. Naam van deze service in de .env van `aas` stoppen. Commando toevoegen aan sudoërs file zodat `aas` deze service kan callen
- [x] timer toevoegen aan service?
- [x] Na deploy: GitHub en Contentful webhook linken

**Comment by tomwassenberg** [comment]
This has been fixed by #209! https://svsticky.nl/ :tada:

The old WordPress resides at https://old.svsticky.nl/ for now.
