### ISSUE TITLE
Disabling of exec(ut) and related subdomains

### ISSUE THREAD

**Issue by RCdeWit** [svsticky/sadserver#214]
Could the following exec(ut) subdomains be disabled?

- speakers.execut.nl
- partners.execut.nl
- display.execut.nl

Additionally, there's a domain that's no longer current. Perhaps it could be archived as idata.svsticky.nl or disabled entirely.

- symposium.svsticky.nl

Then there's two extra old sites without a valid certificate. Perhaps these could be disabled as well. Alternatively, their certificate should be renewed.

- futuretechnologies.svsticky.nl
- darksideofit.svsticky.nl

**Comment by maartenberg** [comment]
The last two domains don't actually exist and get routed, this is just the wildcard redirecting to the normal site, the certificate error also shows that "The certificate is only valid for the following names: stickyutrecht.nl, studieverenigingsticky.nl, svsticky.nl, www.stickyutrecht.nl, www.studieverenigingsticky.nl, www.svsticky.nl".

**Comment by HugoPeters1024** [comment]
Fixed in https://github.com/svsticky/sadserver-secrets/pull/9/commits with `symposium` disabled entirely
