### ISSUE TITLE
File sharing

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#215]
The board needs to have a way to share files using semi-public links. The current workflow is to upload a file to the Wordpress store, and then link the file's URL in `wp-uploads`, but this won't work anymore when the new website is deployed.

Must:
- Board uploads files
- Members can download files

Unknown:
- Do we want an index of the uploaded files? This could be useful for for instance an archive of ALV minutes, but there could also be cases where we don't want to show every file.
- Do we want to restrict downloads to active members via Koala login?

We could for instance do this by using nginx' [`fancyindex` feature](https://www.nginx.com/resources/wiki/modules/fancy_index/) for a public directory and a normal webroot for any non-public files. This would allow the board to just `scp` files in place, which works, but isn't extremely board-friendly.

@ckef

**Comment by duijf** [comment]
> Do we want an index of the uploaded files? This could be useful for for instance an archive of ALV minutes, but there could also be cases where we don't want to show every file.

There is `fancyindex_ignore` which can take a regex. If we put stuff in a separate dir, we can easily make certain files public or private

**Comment by Ckef** [comment]
> * Do we want an index of the uploaded files? This could be useful for for instance an archive of ALV minutes, but there could also be cases where we don't want to show every file.

At least non-public, I don't think we really need a public index for now. To be sure I'll mention it during a meeting next friday.

**Comment by duijf** [comment]
I do think there might be value in having an actual archive of ALV minutes. Otherwise people have to go diving into their email if they want to check the previous stuff. And people who have joined this year, might have an interest in stuff from previous years (might still be relevant as well)

**Comment by tomwassenberg** [comment]
> Do we want to restrict downloads to active members via Koala login?

This would be nice, and quite easy when #199 is fixed :)

**Comment by Ckef** [comment]
> * Do we want an index of the uploaded files? This could be useful for for instance an archive of ALV minutes, but there could also be cases where we don't want to show every file.
Yes, we would also like to upload things such as "KB info uurtje slides", general files any Sticky member might want to read again, some sort of folder structure would be nice. Targeting specific files to be visible or not is a nice could have, not a real must for now.

> * Do we want to restrict downloads to active members via Koala login?
Yes, more specifically, restrict viewing them via Koala login.

**Comment by duijf** [comment]
We should be able to do this without recompiling nginx (I hope). Ubuntu seems to package https://packages.ubuntu.com/bionic/libnginx-mod-http-fancyindex

**Comment by tomwassenberg** [comment]
Fixed by #223!
