### ISSUE TITLE
Archive old.svsticky.nl

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#230]
- Archive dump of database and files to S3
- Set relevant steps in the Ansible playbook to absent or comparable
- Run that on the test server
- Check if everything is gone
- Run it on the live server
- Remove relevant steps from playbook

**Comment by Riscky** [comment]
some files are still hosted on the old webroot

**Comment by Riscky** [comment]
Backups have been made, relevant files can be migrated to public.svsticky.nl
