### ISSUE TITLE
Pin Ansible and Mitogen versions using Nix

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#248]
We have people on different Linux distibutions (I use Arch btw), and e.g. Ubuntu does
not ship major package updates unless your project is special (Firefox) or you use a
PPA.

I ran into issues today because I accidentally updated my Ansible version, which
broke Mitogen, and I had to manually download a new Mitogen version like some sort of
caveman.

We can ensure that everyone is using the exact same Ansible and Mitogen versions, no
matter which distribution they're using, if we would pin this using Nix.

**Comment by Riscky** [comment]
Fixed
