### ISSUE TITLE
Rewrite `run-playbook.sh` in Python

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#261]
We could have this script:
- Check whether Bitwarden is unlocked before starting a run to prevent immediately crashing (#250)
- Check and validate required parameters
- Don't be Bash
- Have a flag to prevent sending chat spam and/or allow sending chat spam to the deploying user instead of `#notifications`

**Comment by HugoPeters1024** [comment]
What exactly is the benefit of rewriting this to python. Surely the bitwarden check can be done in bash as well. Is it really worth the hassle?

**Comment by HugoPeters1024** [comment]
Bonk, go to bash jail
