### ISSUE TITLE
Fix websites that copy their own custom nginx conf and use the built in list (like savadaba)

### ISSUE THREAD

**Issue by HugoPeters1024** [svsticky/sadserver#266]

**Comment by SilasPeters** [comment]
If I understand #365 correctly, we can now close this issue as we use roles now. Is that correct @Riscky ?

**Comment by Riscky** [comment]
Tbh I never really understood the purpose of this issue, so you'll have to ask @HugoPeters1024

**Comment by HugoPeters1024** [comment]
Wow that was a terrible documented issue. I have no idea what it was about 🤣 . Closing

**Comment by SilasPeters** [comment]
Haha thanks guys! Another 3 year old issue closed
