### ISSUE TITLE
Restrict webroots to board member / committee access

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#267]
The board / @Riscky want to restrict access for certain webroots to not only authenticated users, but also a subset of these users, like only the board or some committees.

We have a few options for this:
- Run separate instances of `oauth2-proxy` in which we pass some file to the `--authenticated-emails-file` option listing the emails of the users that are allowed to authenticate.
- Change Koala to add a special `verify-admin` scope that can only be granted to admin accounts, require this scope when loading an admin-only webroot
- Use Google groups to authenticate (usable for board, but probably not for committees): https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#restrict-auth-to-specific-google-groups-on-your-domain-optional
- Use Github teams to authenticate (probably usable for both but still requires running multiple proxy instances): https://oauth2-proxy.github.io/oauth2-proxy/auth-configuration#github-auth-provider

All of these options require running multiple instances of oauth2_proxy, which is possible but a little bit annoying. We could also look if there's another proxy that does allow different authorization policies for different upstreams.

**Comment by Riscky** [comment]
I think we want to go for the first option

**Comment by HugoPeters1024** [comment]
Although I am not terribly educated on the subject, after some discussion and evaluation 1 also seems the best to me.
