### ISSUE TITLE
Monitor whether cronjobs actually run

### ISSUE THREAD

**Issue by maartenberg** [svsticky/sadserver#298]
We have some cronjobs (like the backups) that we would very much like to run periodically.
We have configured most of these tasks to have a Systemd on-failure handler to ensure we get messaged on Slack if one of these jobs fail.
However, we do not get notified if the cronjobs never run, which could be bad.

There is a service called [healthchecks.io](https://healthchecks.io/) that can do this for us, this works by pinging a webhook after the job is done. We might want to look into setting this up.

**Comment by Riscky** [comment]
This has been done
