### ISSUE TITLE
Rename intro.svsticky.nl to signup/inschrijven.svsticky.nl

### ISSUE THREAD

**Issue by Riscky** [svsticky/sadserver#401]
The current naming makes it easy to confuse with intro-cs.svsticky.nl
Mind that this requires changes in Koala, sadserver and static-sticky (and possibly intro-cs.svsticky.nl).
In Koala the host configuration needs to updated.
In sadserver the nginx configuration needs to be updated.
In static-sticky (and possibly intro-cs.nl) the links have to be updated.

**Comment by SilasPeters** [comment]
Right now intro.svsticky still exists. We might want to remove this endpoint, but this issue is closed as per #427.
